local M = {}

-- NOTE: Search more icons: https://www.nerdfonts.com/cheat-sheet
M.icons = {
  misc = {
    dots = '󰇘',
  },
  dap = {
    Stopped = { '󰁕 ', 'DiagnosticWarn', 'DapStoppedLine' },
    Breakpoint = ' ',
    BreakpointCondition = ' ',
    BreakpointRejected = { ' ', 'DiagnosticError' },
    LogPoint = '.>',
  },
  diagnostics = {
    -- Error = '● ',
    -- Warn = '● ',
    -- Hint = '● ',
    -- Info = '● ',
    Error = ' ',
    Warn = ' ',
    Hint = ' ',
    Info = ' ',
  },
  file = {
    modified = ' ',
    readOnly = ' ',
    default = '󰈙 ',
  },
  fold = {
    closed = ' ',
    opened = ' ',
    separator = ' ',
  },
  folder = {
    closed = ' ',
    empty = ' ',
    open = ' ',
  },
  git = {
    added = ' ',
    modified = ' ',
    removed = ' ',
    branch = ' ',
    conflict = ' ',
    ignored = '◌ ',
    renamed = '➜ ',
    staged = '✓ ',
    unstaged = '✗ ',
    untracked = '★ ',
  },
  kinds = {
    Array = ' ',
    Boolean = '󰨙 ',
    Class = ' ',
    Codeium = '󰘦 ',
    Color = ' ',
    Control = ' ',
    Collapsed = ' ',
    Constant = '󰏿 ',
    Constructor = ' ',
    Copilot = ' ',
    Enum = ' ',
    EnumMember = ' ',
    Event = ' ',
    Field = ' ',
    File = ' ',
    Folder = ' ',
    Function = '󰊕 ',
    Interface = ' ',
    Key = ' ',
    Keyword = ' ',
    Method = '󰊕 ',
    Module = ' ',
    Namespace = '󰦮 ',
    Null = ' ',
    Number = '󰎠 ',
    Object = ' ',
    Operator = ' ',
    Package = ' ',
    Property = ' ',
    Reference = ' ',
    Snippet = ' ',
    String = ' ',
    Struct = '󰆼 ',
    TabNine = '󰏚 ',
    Text = ' ',
    TypeParameter = ' ',
    Unit = ' ',
    Value = ' ',
    Variable = '󰀫 ',
  },
}
M.palettes = {
  catppuccin = {
    rosewater = '#f5e0dc',
    flamingo = '#f2cdcd',
    pink = '#f5c2e7',
    mauve = '#cba6f7',
    red = '#f38ba8',
    maroon = '#eba0ac',
    peach = '#fab387',
    yellow = '#f9e2af',
    green = '#a6e3a1',
    teal = '#94e2d5',
    sky = '#89dceb',
    sapphire = '#74c7ec',
    blue = '#89b4fa',
    lavender = '#b4befe',
    text = '#cdd6f4',
    subtext1 = '#bac2de',
    subtext0 = '#a6adc8',
    overlay2 = '#9399b2',
    overlay1 = '#7f849c',
    overlay0 = '#6c7086',
    surface2 = '#585b70',
    surface1 = '#45475a',
    surface0 = '#313244',
    base = '#1e1e2e',
    mantle = '#181825',
    crust = '#11111b',
  },

  everforest = {
    bg_dim = '#232A2E',
    bg0 = '#2D353B',
    bg1 = '#343F44',
    bg2 = '#3D484D',
    bg3 = '#475258',
    bg4 = '#4F585E',
    bg5 = '#56635f',
    bg_visual = '#543A48',
    bg_red = '#514045',
    bg_green = '#425047',
    bg_blue = '#3A515D',
    bg_yellow = '	#4D4C43',
    fg = '#D3C6AA',
    red = '#E67E80',
    orange = '#E69875',
    yellow = '#DBBC7F',
    green = '#A7C080',
    aqua = '#83C092',
    blue = '#7FBBB3',
    purple = '#D699B6',
    grey0 = '#7A8478',
    grey1 = '#859289',
    grey2 = '#9DA9A0',
    statusline1 = '#A7C080',
    statusline2 = '#D3C6AA',
    statusline3 = '#E67E80',
  },
}

return M
